# Generated by Django 4.0.1 on 2022-07-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
