# Generated by Django 4.0.5 on 2022-07-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0005_customer_remove_user_is_admin_remove_user_is_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='admin', max_length=10),
        ),
    ]
