# Generated by Django 4.0.5 on 2022-07-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0006_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='seller', max_length=10),
        ),
    ]
